model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: "/home/peiyuan/zhw/model/Llama-2-7b-chat-hf"
  ckpt: "/home/peiyuan/zhw/model/checkpoint_59.pth"
  lora_r: 64
  lora_alpha: 16

datasets:    
  mosei_data_builder:
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 30

evaluation_datasets:
  mosei_data_builder:
    eval_file_path: /home/peiyuan/dataset/CMU-MOSEI/data/final_multi_labels.csv

    img_path: /home/peiyuan/dataset/CMU-MOSEI/data

    max_new_tokens: 500
    batch_size: 1

run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: /home/peiyuan/zhw/MOSEI-Emotion-LLaMA/results